### PR TITLE
Fix a compile error in the Examples project

### PR DESCRIPTION
**Pull request by Numpsy**
I tried building this whilst looking at something else, and it failed to compile with an error about ```TryGetBytes``` not existing.
Has it got out of step with the recent spanification changes?

### CODE REVIEW

**Comment by Numpsy** [comment]
On a related note, the examples project is built as ```netcoreapp2.1``` - should it be updated to something newer to go with all the othre recent updates?

**Comment by BobLd** [comment]
Thx a lot for that! Not sure how it didn't raise any issue when merging

> On a related note, the examples project is built as `netcoreapp2.1` - should it be updated to something newer to go with all the othre recent updates?

Not sure tbh, we could target a more recent framework indeed

**Review by BobLd — APPROVED** [review]

**Comment by Numpsy** [comment]
> Not sure tbh, we could target a more recent framework indeed

I suppose that it does have the advantage of running against the netstandard2.0 build of the libraries, now that the unit tests are only targetting higher versions.

**Comment by BobLd** [comment]
Yes exactly, let's leave it like that

**Pull request merged**
