### PR TITLE
DecodeParameterResolver looks in the wrong array when retrieving filter parameters

### PR DESCRIPTION
**Pull request by kasperdaff**

### CODE REVIEW

**Comment by kasperdaff** [comment]
@EliotJones Have you had a chance to look at this?

**Comment by EliotJones** [comment]
@kasperdaff sorry I've been away from the project for a while. Hopefully this weekend I can find some time to look at it. The code looks good I just want to take the time to run the full test set I have locally to check there are no unintended consequences.

**Comment by kasperdaff** [comment]
@EliotJones No worries :-) Thanks in advance!

**Review by EliotJones — APPROVED** [review]
:+1:

**Pull request merged**
