### PR TITLE
Add a unit test for reading document information

### PR DESCRIPTION
**Pull request by Numpsy**
Add a unit test for reading custom properties from the document information (#38)

### CODE REVIEW

**Comment by EliotJones** [comment]
Thanks, this looks good and it should help refactoring this area in future when I/anyone else gets round to it. Thanks again for all your bug reports, they've been extremely useful in making the library more stable for everyone.

I'm just going to wait to see if Appveyor will successfully build this, I don't think it's your changes that are breaking the build, it's just that at weekends the build agents get busy and the builds start timing out (even though the timeout is set to 1hr 30m!). If it doesn't build after a couple of tries I'll merge it anyway.

**Comment by Numpsy** [comment]
I wondered what the situation was with the builds timing out (I mean, given that they don't seem to take much time at all when I run them locally).

**Comment by EliotJones** [comment]
Yeah I'm not really sure what might be causing these timeouts. For now I assume they are due to disk access being very slow on the build machine or something. I imagine the free tier Appveyor build agents are the lowest spec possible.

Hopefully there'll be a free alternative to Appveyor for Windows builds soon, maybe Github will add something.

Since Appveyor has clearly given up today I'll merge this now and check it runs locally.

**Comment by Numpsy** [comment]
> Hopefully there'll be a free alternative to Appveyor for Windows builds soon, maybe Github will add something.
> 

Azure Pipelines has some free support for open source projects, but I couldn't say how performance compares with Appveyor.

**Pull request merged**
