### PR TITLE
Implement TryGetPath and TryGetNormalisedPath for fonts

### LINKED ISSUE #501: Word bounding box without height
I use the Pdfpig ver 0.1.6 and I have some problems with a few pdf files. The bounding box is the line (because it has height = 0). I dont know where the issues exist. 

```
using (PdfDocument document = PdfDocument.Open(bufferFile.ToArray()))
{
	PdfDoc pdfDoc = new PdfDoc(Guid.NewGuid(), path);

	for (var i = 0; i < document.NumberOfPages; i++)
	{
		var page = document.GetPage(i + 1);
		var words = new NearestNeighbourWordExtractor(new NearestNeighbourWordExtractorOptions()).GetWords(page.Letters);
		pdfDoc.pages.Add(new PdfPage(i+1, page.Height, page.Width));

		foreach (var block in words)
		{
			pdfDoc.pages[i].boundingBoxes.Add(new BoundingBox(block.BoundingBox.TopLeft.X, block.BoundingBox.TopLeft.Y, 
												block.BoundingBox.BottomRight.X, block.BoundingBox.BottomRight.Y, 
												block.Text));

		}
	}
}
```
I attached a sample file and some result when I plot the bounding box below. 
image
image
[Baring_Amy Tay_Finance Manager.pdf](https://github.com/UglyToad/PdfPig/files/9859173/Baring_Amy.Tay_Finance.Manager.pdf)

https://github.com/UglyToad/PdfPig/issues/380

### PR DESCRIPTION
**Pull request by BobLd**
- Implement TryGetPath and TryGetNormalisedPath for fonts
- Substiture PdfSubpath by List<PdfSubpath> where necessary
- Fix PdfTextRemoverTests.cs

You can check the [pdf-to-image-skia](https://github.com/UglyToad/PdfPig/tree/pdf-to-image-skia) branch and the new test project for some rendering of these fonts.

fix #501 should also be good now (not sure if related) as letters are rendered correctly

@fnatzke [pdf-to-image-skia](https://github.com/UglyToad/PdfPig/tree/pdf-to-image-skia) might be of interest to you too (does not use skia yet, still system.drawing)

Below are renders examples - only vector based letters are rendered and color is forced to b&w 
Baring_Amy Tay_Finance Manager-1 pdf_1_system-drawing

Pig Production Handbook_1_system-drawing

pop-bugzilla37292 pdf_1_system-drawing

Motor Insurance claim form_1_system-drawing

Type0 Font_1_system-drawing

cat-genetics pdf_1_system-drawing

byz_1_system-drawing

### CODE REVIEW

**Comment by fnatzke** [comment]
@BobLd 

That's great!

Yes very interested in this branch as I think a lot of people will be.

I'm still working on DctDecode and ColorSeparation which should help with rendering effort with images.

Great to see your back at it.

**Comment by BobLd** [comment]
rebased on latest changes, should be good to go

**Comment by prom3theu5** [comment]
Unfortunately still getting height 0 bounding boxes on this PR ( #501 )

image

**Comment by BobLd** [comment]
@prom3theu5 I think the document given in example in #501 now works (even maybe before this PR). I know there are still issue with other font type. I will get back to that in another PR

**Comment by prom3theu5** [comment]
> @prom3theu5 I think the document given in example in #501 now works (even maybe before this PR). I know there are still issue with other font type. I will get back to that in another PR

Ahh no problem - thanks for clarification, and your continued effort - It's greatly appreciated :)

**Review by EliotJones — APPROVED** [review]
approved, not sure if you wanted to merge yet since there are some not implemented exceptions still?

**Comment by BobLd** [comment]
@EliotJones that's good to merge, what's left is same as PdfBox. it's a big chunk of work, happy to come back it it later on

**Comment by BobLd** [comment]
@EliotJones conflict resolved

**Pull request merged**
